SpeakingInBits/PC2

- .github/workflows/dotnet.yml
> Set up CI pipeline

- PC2/Views/Home/About.cshtml
> Center aligned pictures

- PC2/Views/Shared/_Layout.cshtml
> Fixed Hamburger Menu

- PC2/Data/AgencyDB.cs
> Agency names are now filtered to show only one

- PC2/Controllers/ResourcesController.cs
- PC2/Data/AgencyDB.cs
> All agencies including duplicates are shown when selecting a service

- PC2/Controllers/ResourcesController.cs
- PC2/Models/Agency.cs
- PC2/Views/Agency/Index.cshtml
- PC2/Views/Resources/Details.cshtml
- PC2/Views/Resources/ResourceGuide.cshtml
> Agency details can now be seen

- PC2/Views/Shared/_Layout.cshtml
- PC2/wwwroot/css/site.css
> Issue#35 drop down menus

- PC2/Areas/Identity/Pages/Account/Login.cshtml
> Removed external login

- PC2/wwwroot/css/site.css
> Removed underline

- ImportExcel/Program.cs
removed .toString() to avoid null reference exceptions.
> removed .toString()

- PC2/PC2.csproj
> Update .NET 6 RC packages

- PC2/Views/Home/ContactPage.cshtml
- PC2/Views/Shared/_Layout.cshtml
> Added a <br> tag to separate the title

- PC2/Views/Home/ContactPage.cshtml
added phone links on the Contact Page
> Added Phone Links

- PC2/Views/Home/ContactPage.cshtml
- PC2/Views/Resources/ResourceGuide.cshtml
and small responsive spacing issue when form is resized to phone size. Now should not squish weird on small size.
closes #87
> Fixed button Alignment

- PC2/Views/Home/ContactPage.cshtml
- PC2/Views/Home/HousingProgram.cshtml
- PC2/Views/Resources/ResourceGuide.cshtml
- PC2/Views/Shared/_Layout.cshtml
found the phone numbers and emails and added the html tags to have them open either a dialer or email program.
Also turned the phone links back to white in the footer.
closes #54
> Added HTML tags

- PC2/Views/Resources/ResourceGuide.cshtml
> Issue #79 Add city and zip to resource guide results

- PC2/PC2.csproj
- PC2/Program.cs
- PC2/Properties/serviceDependencies.json
- PC2/Properties/serviceDependencies.local.json
- PC2/appsettings.json
Starting work on #36 
Application Insights added to the website
> Adding Azure Application Insights

- .github/workflows/pc2online.yml
The Azure publish workflow will now also run any pending migrations against the production database. Testing will still need to be done manually before the workflow is triggered
> Update pc2online.yml - Add DB Migrations

- PC2/Program.cs
Closes #117 
The production code runs in Release mode, so any code wrapped with ```#if DEBUG``` will not run on the production server
> Issue #117 - Run startup database code in debug only

- PC2/Controllers/ResourcesController.cs
- PC2/Models/ResourceGuideModel.cs
- PC2/Views/Resources/ResourceGuide.cshtml
> Issue#115 resource guide search visuals

- PC2/Views/Home/About.cshtml
- PC2/Views/Home/HousingProgram.cshtml
- PC2/Views/Resources/DisabilityAwareness.cshtml
> Issue #89 image alt attributes

- PC2/Program.cs
- PC2/Views/Home/HousingProgram.cshtml
> Issue #127 - Set default culture to English US

- PC2/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
- PC2/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
- PC2/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
- PC2/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml
- PC2/PC2.csproj
- PC2/Views/Shared/_LoginPartial.cshtml
> Issue #130 and #131 Admin navigation

- PC2/Views/Home/HousingProgram.cshtml
- PC2/Views/Resources/FocusNewsletters.cshtml
> Issue #143 - Open PDF links in new tab

- PC2/Controllers/HomeController.cs
> Issue #142 - Clear Contact Us form after successful message

- PC2/Views/Events/Index.cshtml
> Issue #152 - Add message when there are no events/activities to display

- PC2/Controllers/CalendarController.cs
> Issue #151 - Event edit start/end time

- PC2/Controllers/ResourcesController.cs
> Implement manual resource guide searches. Refactor telemetry code

- PC2/Views/Resources/FocusNewsletters.cshtml
> Issue #170 - Fall 2022 Newsletter

- PC2/Data/AgencyCategoryDB.cs
> Issue #169 - Sort Agency Categories in alphabetical order

- PC2/Controllers/AboutController.cs
- PC2/Data/BoardDB.cs
- PC2/Data/StaffDB.cs
> Issue #168 - Staff/Board member order for Admin pages

- PC2/Views/Shared/_Layout.cshtml
> Removed unnecessary li nav-item

- PC2/Views/About/HousingProgramData.cshtml
closes #139 
This should dynamically create anchor tags based on household size, which should be a unique number in this case. I'm not sure how to test if it is pulling to the correct entry.
> Kriston issue#139 update admin housing program page

- PC2/Views/Shared/_Layout.cshtml
> Removed unnecessary nav-item to get rid of highlight anomaly and fix dropdown alignment

- PC2/Views/About/EditStaff.cshtml
> User can now edit priority order.

- PC2/Controllers/CalendarController.cs
- PC2/Controllers/EventsController.cs
- PC2/Data/CalendarEventDB.cs
- PC2/Views/Calendar/Index.cshtml
- PC2/Views/Events/Index.cshtml
> Reversed the order of events to chonological order (oldest first).

- PC2/Views/ProgramVideos/Index.cshtml
> Rotated video links, updated heading.

- PC2/Views/Shared/_Layout.cshtml
- PC2/wwwroot/css/site.css
Closes #204 
Do these colors look good or should I adjust them more?
> Michael Forbes issue#204 contrast

- PC2/Data/AgencyDB.cs
Resolves #215 
Admin agency list now sorted in alphabetical order by name
> Admin agency list now sorted in alphabetical order by name

- PC2/Controllers/HomeController.cs
- PC2/Views/Home/PartnersForHousing.cshtml
- PC2/Views/Shared/_Layout.cshtml
> Issue #209 - Add partners4Housing page

- PC2/Views/Home/Index.cshtml
> Changed max-width to match picture disappearance

- PC2/wwwroot/css/site.css
> Changed margin on container class to auto instead of 0

- PC2/Views/Shared/_Layout.cshtml
- README.md
The ARIA IDS are now unique.
<p class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink1"
<p class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink2"
Resolves #205
> The duplicates for the ARIA IDs are now unique.

- PC2/Views/Home/Index.cshtml
Client wanted more specific formatting on #251
> Add line break to mission statement text

- PC2/Models/NewsletterFile.cs
Closes #238 
Documented the class NewsLetterFile, and all of its fields. Let me know if you want me to add more detail or change it overall.
> First attempt at documenting the NewsLetterFile

- PC2/Views/Resources/FocusNewsletters.cshtml
- PC2/wwwroot/js/edit.js
> Joe issue#256 newsletter download metrics

- PC2/Models/Agency.cs
- PC2/Views/Home/Index.cshtml
Closes #233 
Documented Agency class and all related fields.
Documented AgencyDisplayViewModel and all related fields.
Let me know if any documentation does not fit the requirements or is inaccurate.
> Documented Agency Class and all related fields

- PC2/Models/AgencyCategory.cs
Closes #235 
Documented the AgencyCategory class.
Documented all fields contained by AgencyCategory.
> Documented AgencyCategory and all contained fields

- PC2/Views/Resources/ResourceLinks.cshtml
Client requested a new link be added to the ResourceLinks page
> Add resource link on client request

- PC2/Views/NewsToKnow/Index.cshtml
> Removed designated section from News To Know view

- PC2/Views/Home/About.cshtml
> Added Cary Vazquez to the alt text on about page

- PC2/Views/Shared/_Layout.cshtml
Added aria labels for Twitter and Facebook icon links
Closes #202
> Issue #202: Social links have screen reader support 

- PC2/wwwroot/css/site.css
> Increased font-size for navigation

- PC2/Views/ProgramVideos/Index.cshtml
Added alt tag to the film image on /ProgramVideos page
> Added an alt tag to the image on the /ProgramVideos page

- .github/workflows/dotnet.yml
- .github/workflows/pc2online.yml
- PC2/PC2.csproj
Closes #289 
Upgrading project and CI pipelines to .NET 8
> Issue#289 .NET 8 Upgrade

- PC2/Views/Home/ContactPage.cshtml
This is related to #295 
We removed the contact form and then updated the layout of the page to make the existing contact info look better
> Issue#295 - Remove contact form

- PC2/Views/Shared/_Layout.cshtml
- PC2/wwwroot/css/site.css
Fixed the navigation bar and the dropdown menus.
Closes #222
> Issue#222 - Navigation Bar

- PC2/wwwroot/css/site.css
Fixed the site.css file improper indentation.
Closes #300
> Issue#300 - site.css indentation

- PC2/wwwroot/css/news.css
> removed empty body selector

- PC2/Models/EventsModel.cs
> Initialized a CalendarEvents property with an empty collection

- PC2/Controllers/AboutController.cs
Updated AboutController so that ConfirmDeleteStaff, ConfirmDeleteBoard, and ConfirmDeleteSteeringCommittee methods no longer contain non-nullable type errors. closes #303
> Pull Request for Issue #303

- PC2/Views/ProgramVideos/Index.cshtml
> Update program videos

- PC2/Views/ProgramVideos/Index.cshtml
Program videos page had the wrong quarter
> Update program videos heading

- PC2/Views/ProgramVideos/Index.cshtml
Client wanted the heading changed
> Update program video header text

- PC2/Views/Resources/ResourceLinks.cshtml
Client discovered some outdated links on their ResourceLinks page. They provided they updates
> Update resource links page

- PC2/Views/Shared/_Layout.cshtml
Closed #315 
Move these tabs (Resource Guide, Focus Newsletters) from the dropdown menu (Resources) to the main navigation.
> Refactor the navigation

- PC2/PC2.csproj
Updated the Microsoft.ApplicationInsights.AspNetCore package to the latest stable version 2.22.0
> Updated the Microsoft.ApplicationInsights.AspNetCore

- PC2/PC2.csproj
Using manage NuGet packages for Solution in the tools tab. Version 9.0 is available for the NuGet packages if we update the framework to net9.0 in the PC2.csproj file.
> Updated NuGet packages Jovanni Ramirez

- PC2/Controllers/AboutController.cs
- PC2/Models/HousingProgram.cs
Closed #324 
Refactor HousingProgramData method, using Model Binding appropriately
> Refactor HousingProgramData method, using Model Binding appropriately

- PC2/Areas/Identity/Pages/Account/Login.cshtml.cs
> Fixed all current possible null warnings on the Login page

- PC2/Views/Shared/_Layout.cshtml
Client requested that all the navigation links on the banner be changed to title case
> Update navigation labels to title case in _Layout.cshtml

- PC2/Controllers/EventsController.cs
- PC2/Data/CalendarEventDB.cs
- PC2/Models/EventsModel.cs
- PC2/Views/Events/Index.cshtml
Removed event type distinction from EventsController and EventsModel. Updated views to reflect changes, including static titles and improved layout. Added CSS for visual differentiation of events and modified JavaScript for event color coding.
Used code from #363 Standing meetings were left out upon client request
> Merge Event Calendar

- PC2.sln
- PC2/Models/RendererHelper.cs
- PC2/Program.cs
- PC2/Views/Resources/Details.cshtml
- PC2/Views/Resources/ResourceGuide.cshtml
- PC2Tests/Models/RendererHelperTests.cs
- PC2Tests/PC2Tests.csproj
& a first step on refactoring to RendererHelper
I implemented a unit test and have 4 passing test. But I haven't viewed every page of phone numbers. I can see that it worked for the case of random 3 letters like (abc) for the test case I setup. 
closes #372
> Bug fix for phone number rendering
